dist: xenial
sudo: false

language: python
python:
  # ST3 uses 3.3 internally, but flake8 (pyflakes) requires 3.4,
  # which is also the last image available on xenial.
  - "3.4"

# branches:
#   except:
#     - /^v\d/

install:
  - pip install flake8==3.7.8
  # fetch syntax testing binary
  - wget --content-disposition https://download.sublimetext.com/latest/dev/linux/x64/syntax_tests
  - tar xf "$(ls st3_syntax_tests_build_*_x64.tar.bz2)"
  - rm -R st3_syntax_tests*.tar.bz2
  - mv st3_syntax_tests ..

before_script:
  # setup portable testing env & fetch default packages
  - mkdir ../st3_syntax_tests/Data
  - git clone --depth=1 https://github.com/sublimehq/Packages.git ../st3_syntax_tests/Data/Packages  # --branch=v3157
  - ln -s "$PWD" ../st3_syntax_tests/Data/Packages/PackageDev

script:
  - ../st3_syntax_tests/syntax_tests
  - flake8 .
